apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values.app .Values.environment "Name" }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "nginx.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
