fido:
  config:
    APP_PORT: "8080"
    APP_NAME: "helm-java-app-new-cm"
    SERVER_PORT: "8080"
    DB_PORT: "1234"

  envFromConfigMap:
    - name: APP_PORT
      key: APP_PORT
    - name: APP_NAME
      key: APP_NAME
    - name: DB_PORT
      key: DB_PORT
  configMapName: test-configmap-new
